---
name: CI

"on":
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  pre-commit:
    name: Pre-Commit & Automated Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Run Pre-Commit via Shared Action
        uses: bumuellp/lights-camera-bum-action/pre-commit@ae01536f0debbf5f18a99887f55186df4b53b997
