---
name: Deploy GitHub Pages

"on":
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-pages:
    name: Deploy
    uses: bumuellp/lights-camera-bum-action/.github/workflows/deploy-pages.yml@0d93c673fba580fb1da0442bef564e423ab7ae0b
    with:
      build-command: "npm run build"
      dist-path: "./dist"
