---
name: Deploy GitHub Pages

"on":
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy-pages:
    name: Deploy
    uses: bumuellp/lights-camera-bum-action/.github/workflows/deploy-pages.yml@main
    with:
      build-command: "npm run build"
      dist-path: "./dist"
